// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WeightApp.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AddMealRequest
    {
        /// <summary>
        /// Initializes a new instance of the AddMealRequest class.
        /// </summary>
        public AddMealRequest() { }

        /// <summary>
        /// Initializes a new instance of the AddMealRequest class.
        /// </summary>
        public AddMealRequest(int mealTypeId, int productId, int goalId, int amount, DateTime date)
        {
            MealTypeId = mealTypeId;
            ProductId = productId;
            GoalId = goalId;
            Amount = amount;
            Date = date;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mealTypeId")]
        public int MealTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "productId")]
        public int ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "goalId")]
        public int GoalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public int Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public DateTime Date { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
