// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WeightApp.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DailyMealInstanceModel
    {
        /// <summary>
        /// Initializes a new instance of the DailyMealInstanceModel class.
        /// </summary>
        public DailyMealInstanceModel() { }

        /// <summary>
        /// Initializes a new instance of the DailyMealInstanceModel class.
        /// </summary>
        public DailyMealInstanceModel(DateTime dateTime, double dailyNorm, double consumed, IList<MealInstanceModel> meals = default(IList<MealInstanceModel>))
        {
            DateTime = dateTime;
            DailyNorm = dailyNorm;
            Consumed = consumed;
            Meals = meals;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateTime")]
        public DateTime DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dailyNorm")]
        public double DailyNorm { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consumed")]
        public double Consumed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "meals")]
        public IList<MealInstanceModel> Meals { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Meals != null)
            {
                foreach (var element in this.Meals)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
