// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WeightApp.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GoalModel
    {
        /// <summary>
        /// Initializes a new instance of the GoalModel class.
        /// </summary>
        public GoalModel() { }

        /// <summary>
        /// Initializes a new instance of the GoalModel class.
        /// </summary>
        public GoalModel(int goalId, DateTime startDate, int weight, int weightGoal, int height, bool isCompleted, bool isSuccess)
        {
            GoalId = goalId;
            StartDate = startDate;
            Weight = weight;
            WeightGoal = weightGoal;
            Height = height;
            IsCompleted = isCompleted;
            IsSuccess = isSuccess;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "goalId")]
        public int GoalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDate")]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public int Weight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weightGoal")]
        public int WeightGoal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public int Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isCompleted")]
        public bool IsCompleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isSuccess")]
        public bool IsSuccess { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
