// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WeightApp.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class RegisterUserResponse : RegisterUserRequest
    {
        /// <summary>
        /// Initializes a new instance of the RegisterUserResponse class.
        /// </summary>
        public RegisterUserResponse() { }

        /// <summary>
        /// Initializes a new instance of the RegisterUserResponse class.
        /// </summary>
        public RegisterUserResponse(string email, string password, string name, bool isMale, DateTime dateOfBirth)
            : base(email, password, name, isMale, dateOfBirth)
        {
        }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
