// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WeightApp.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SetNewGoalRequest
    {
        /// <summary>
        /// Initializes a new instance of the SetNewGoalRequest class.
        /// </summary>
        public SetNewGoalRequest() { }

        /// <summary>
        /// Initializes a new instance of the SetNewGoalRequest class.
        /// </summary>
        public SetNewGoalRequest(int weight, int weightGoal, int height, DateTime startDate)
        {
            Weight = weight;
            WeightGoal = weightGoal;
            Height = height;
            StartDate = startDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public int Weight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weightGoal")]
        public int WeightGoal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public int Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDate")]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
        }
    }
}
