// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WeightApp.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdateUserResponse : UpdateUserRequest
    {
        /// <summary>
        /// Initializes a new instance of the UpdateUserResponse class.
        /// </summary>
        public UpdateUserResponse() { }

        /// <summary>
        /// Initializes a new instance of the UpdateUserResponse class.
        /// </summary>
        public UpdateUserResponse(bool isMale, DateTime dateOfBirth, string password = default(string), string name = default(string), string email = default(string))
            : base(isMale, dateOfBirth, password, name)
        {
            Email = email;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
