// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WeightApp.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdateUserRequest
    {
        /// <summary>
        /// Initializes a new instance of the UpdateUserRequest class.
        /// </summary>
        public UpdateUserRequest() { }

        /// <summary>
        /// Initializes a new instance of the UpdateUserRequest class.
        /// </summary>
        public UpdateUserRequest(bool isMale, DateTime dateOfBirth, string password = default(string), string name = default(string))
        {
            Password = password;
            Name = name;
            IsMale = isMale;
            DateOfBirth = dateOfBirth;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isMale")]
        public bool IsMale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateOfBirth")]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
